queue_rules:
  - name: default
    merge_conditions:
      - check-success=this-check-never-exists

pull_request_rules:
  - name: auto queue on green CI
    conditions:
      - base=main
      - check-success=proof
    actions:
      queue:
        name: default
