queue_rules:
  - name: default
    merge_conditions:
      - check-success=gate

pull_request_rules:
  - name: auto queue when approved
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
